### ISSUE TITLE
Questions for using io_loadspec_bruk.m file

### ISSUE THREAD

**Issue by YoonhoH** [CIC-methods/FID-A#23]
Dear FID-A community,

I would like to ask for your kind support.

I have questions related to reading Bruker MRS file (.fid or .raw) while using FID-A software.
If you look at the manual related to 9.4T animal Bruker MR, the file format (.fid) consists of real part (int32) followed by imaginary part (int32) - (each data point is written as a pair of words).

Q1)
In inputOutput folder, looking into the file (io_loadspec_bruk.m (line 50~52), I think as follows: real_fid = fid_data(1:2:length(fid_data)); imag_fid = fid_data(2:2:length(fid_data)); fid_raw = real_fid + i*imag_fid, I wonder what you think.  

Q2)
I know that fid_raw is data in time-domain, then, I think that fid_raw should be done with fft computation to acquire spectrum (line 69). I wonder why you do ifft computation.

Have a happy day.

**Comment by jamienear** [comment]
Hello, 

Good questions. Please see my responses below:

Q1)  I agree that this is a strange way of reading the data, but I can't quite remember why it was done this way.  Fortunately, the difference between your suggestion and the way it is currently coded does not really change the result much (implementing the change you suggest would just result in the exact same data, but just with a 90 degree phase shift. This is not too serious since the data rarely come out with perfect phase anyway).  

Q2)  Again, yes I agree that using ifft is a strange way to do it, but I don't have a great explanation for it.  This somehow became the convention in FID-A a long time ago, for reasons that I can't quite remember.  Again, I don't think it has any particularly adverse effects, besides being a bit unconventional.

Thanks for pointing these out.  I will look into whether it is possible to fix these issues; but I likely will not be able to do it right away, since I don't think it is too critical.  Definitely addressing point #2 above would constitute a fairly major change, because fftshift(ifft(fid)) is used in a lot of different functions.  

Best wishes, 
Jamie
